version: 2
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/node:9.9.0
    steps:
      - checkout
      - restore_cache:
          keys:
            - test-{{ .Branch }}-{{ checksum "package-lock.json" }}
            - test-{{ checksum "package-lock.json" }}
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: test-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run: npm run lint
